### ISSUE TITLE
Can't make `redirect_to` with `cablecar` functionnal with `rc2`

### ISSUE THREAD

**Issue by jibees** [hopsoft/cable_ready#272]
This code is functional for `pre10`:

```ruby
        render operations: cable_car.redirect_to(
          url: MY_URL
        )
```

Response is:
```json
[{"url":"/","operation":"redirectTo"}]
```

Unfortunately, when bumping to `rc2`, with the following code:
```ruby
        render cable_ready: cable_car.redirect_to(
          url: MY_URL
        )
```
(only changing deprecated `operations`: to `cable_ready`) it does not redirect my app, probably because the response is actually empty.

 - **Note 1**: if I use `operations:` instead of `cable_ready:` I had a deprecated warning, but the response is still empty.
```
DEPRECATED: CableReady's `render operations:` call has been renamed to `render cable_ready:`. Please update your render call.
```
 - **Note 2**: Running this request is a spec environnement seems ok (at a request level, not browser one), but not in browser. 
 - **Note 3**: 
```ruby
        cable_car.redirect_to(
          url: return_url_or_default(after_sign_in_path_for(spree_current_user))
        )
```
seems ok and is equal to: `#<CableReady::CableCar:0x00007fe3be5ecf28 @enqueued_operations=[{"url"=>"/", "operation"=>"redirectTo"}], @identifier="CableCar", @previous_selector=nil>`

(at least json seems fine)

 - **Note 4**: debugging with firefox give me another clue: the response is not empty and seems to be valid (ie. the right json). On Chrome, the response is still empty. Which seems to be a bit strange.

**Comment by jibees** [comment]
After some research, it appears that the underlying issue was something related to `Content-Type`.

 - The request header Accept was `Accept: application/vnd.cable-ready.json, */*` 
 - The response header Content-Type was `Content-Type text/vnd.cable-ready.json; charset=utf-8``

Actually, `cable_ready` changed its default ContentType recently (reference: https://github.com/stimulusreflex/cable_ready/pull/260)

And the form was actually submitted/handled via [mrujs](https://mrujs.com/) integrated with CableCar which clearly precise that form with accept header `"application/vnd.cable-ready.json, */*"` will be handled
Source: https://mrujs.com/how-tos/integrate-cablecar

So, it's not actually a `cable_ready` issue. Closing here!


_Thanks for the great debugging session @marcoroth ! That was very pleasant!_

**Comment by jibees** [comment]
Just opened a PR on mrujs: https://github.com/KonnorRogers/mrujs/pull/209 !

**Comment by marcoroth** [comment]
Awesome, thank you @jibees!
