### ISSUE TITLE
Question: Would you consider this intended behaviour?

### ISSUE THREAD

**Issue by franks921** [hopsoft/cable_ready#41]
Hi

I've got a fairly complex ActionCable broadcast updating multiple UI blocks on a page when a user comes online or goes offline. Here is a redacted version of the UI I am working on.

![Healthforce - Nurse Sethu Huel 2020-05-26 14-07-21](https://user-images.githubusercontent.com/655991/82899042-97bf6f80-9f5a-11ea-99dd-7fbba4e7eb96.png)

* Red block: Updates using `textContent`
* Green block: Updates using `addCssClass` / `removeCssClass`
* Blue block: Updates by adding and remove pink blocks using `insertAdjacentHTML` and `remove`

So everything is working fine using the code below:

```ruby
channel = cable_ready['UserStatus']
channel.text_content(selector: '[data-target="user.onlineCount"]', text: User.online.count)
channel.add_css_class(selector: '[data-target="user.button"]', name: 'some-css')
channel.insert_adjacent_html(selector: '[data-target="user.list"]', html: '<div>...</div>')
channel.broadcast
```

My question is... was this intended behaviour, and if not, how do you propose I deal with my use-case? I found a caveat which made me wonder if I am doing the correct thing and that's when try and use `channel.remove(selector: '#whatever')` before `channel.insert_adjacent_html`. The html component never appears and I am guessing this has to do with the order of `remove` in relation to `insert_adjacent_html` in https://github.com/hopsoft/cable_ready/blob/master/lib/cable_ready/channel.rb#L201-L220. So it adds it and then removes because of the order of `data.operations`.

**Comment by hopsoft** [comment]
This is not intentional but it does make sense. My recommendation would be to try emitting 2 distinct broadcasts and see if that works out.

1. First broadcast `insert_adjacent_html`
2. Second broadcast `remove`

**Comment by franks921** [comment]
Thanks for the response @hopsoft.

I decided to handle removal in my stimulus controller that setups the channel, using the cable_ready JS events. I want to handle everything with a single broadcast. It's not ideal, but it is a lot simpler than my vanilla implementation.
