### ISSUE TITLE
current_user concerns?

### ISSUE THREAD

**Issue by ultrawebmarketing** [hopsoft/cable_ready#54]
My apologies if this isn't the right place for this, but when playing with cableready over the weekend I ran into an issues where one of my partials is using a method `current_user`.is_admin?` to determine if a piece of code should be rendered on the frontend if the user has admin rights. I commented out the code just to continue with my exploration, however I wonder if anyone has considered how to handle user permissions with something like cableready?

**Comment by leastbad** [comment]
Hey there! You should check out the #cableready channel on Discord: https://discord.gg/XveN625

More documentation is in the works. In the meantime, happy to work this out with you.

First of all, can you tell us how your ActionCable connections are being authenticated, if at all?

https://docs.stimulusreflex.com/authentication

**Comment by ultrawebmarketing** [comment]
thank you so much for taking the time to reply. that looks exactly  what i was trying to do. i will give it a go :)
