### ISSUE TITLE
Event Dispatch: help with serialization

### ISSUE THREAD

**Issue by anaice** [hopsoft/cable_ready#59]
Hi guys. Can you help me with a question?
I'm using cable_ready to dispatch a custom DOM event. When I retrieve event.detail it is in camelCase, I would like it to keep my attributes format. Example: `user_id`, not `userId`
```ruby
   def trigger_dom_evt_new_driver_position(user_id, tracking)
     #...
     cable_ready[stream_name].dispatch_event(
        name: evt_id,
        detail:  { user_id: user_id, tracking: TrackingBlueprint.render_as_hash(tracking) },
        selector: "#operational-map-controller"
     )
     cable_ready.broadcast
   end
```
is there any configuration for serialization?

thank you very much

**Comment by leastbad** [comment]
@hopsoft fwiw I agree with @anaice that we shouldn't automatically camelize details. Sadly, fixing this is a breaking minor change.

**Comment by hopsoft** [comment]
I'm a strong believer in the **"When in Rome, do as the Romans do"** philosophy. Most JavaScripters will expect `camelCase` on the JavaScript side while Rubyists expect `snake_case`, but I do like the idea of making it configurable. 

I'd support a PR that makes it configurable that defaults to `camelCase`.

**Comment by leastbad** [comment]
Fair enough. I do think that it's one of the many things that we should explicitly spell out in the documentation. I'll put it on the list!

If @anaice or anyone else is interested in tackling this, please note that we actually do now have support for configuration options via an initializer. Apologies for the awkward lack of real documentation, but you can get the idea from #47.

In short, a `config.details_case` option (or a better name!) is totally doable.

**Comment by anaice** [comment]
Hi guys. I made a pull request for this.
Please forgive any nonsense: old programmer, but new rubyist here.

**Comment by leastbad** [comment]
Rafael, this is amazing news! I haven't even seen the PR yet, but I want to express how proud I am to see you do this.

If it needs work, we'll help.

**Comment by anaice** [comment]
Thanks! Please let me know if I need to improve the PR.
