### ISSUE TITLE
Operations go missing before broadcasting

### ISSUE THREAD

**Issue by barrywoolgar** [hopsoft/cable_ready#64]
Hello

First off, thank you for this excellent gem. I'm running 4.3.0, and developing on OSX with Ruby 2.7.1 and Rails 6 master.

I believe I've found a concurrency problem in the `CableReady::Channels` singleton.

My app will occasionally enqueue 1000s of Sidekiq jobs in a very short period of time, each of which will generate a small number of morph operations and then broadcast them. A rather small percentage of these jobs will consistently fail inside cable_ready, be re-queued, and later succeed once the queue has shrunk.

The error is: 

    NoMethodError (undefined method `broadcast' for nil:NilClass):
    cable_ready-4.3.0/lib/cable_ready/channels.rb:56:in `block (2 levels) in broadcast'

And occurs on here:

https://github.com/hopsoft/cable_ready/blob/master/lib/cable_ready/channels.rb#L56

    channels.each { |channel| @channels[channel.identifier].broadcast(clear) }

From what I can see with some debug statements is the `@channels` instance var is an empty hash on line 56, despite having to have had keys/values on line 52 to `select` on line 54.

Unfortunately I'm not very familiar with this kind of problem, so not sure if there's anything I can do to mitigate it from my application code. I'm currently working around it by forcing Sidekiq to have a concurrency of 1, but I'm not sure how performant that would be in production.

My job class for reference:

    class BroadcastJob < ActiveJob::Base
      queue_as :default
      sidekiq_options retry: 5
      include CableReady::Broadcaster

      def perform(object)
        cable_ready["subscription-#{object.subscription_id}"].morph(
          selector: "#object_#{object.id}",
          html: renderer.render(partial: "subscriptions/row", locals: { object: object })
        )

        cable_ready["month-#{object.month_id}"].morph(
          selector: "#object_#{object.id}",
          html: renderer.render(partial: "months/row", locals: { object: object })
        )

        cable_ready.broadcast
      end

      private

      def renderer
        @renderer ||= ApplicationController.renderer.new(https: true)
      end
    end

Many thanks for any assistance you can provide!

**Comment by barrywoolgar** [comment]
On further consideration, I imagine the "missing" operations may have still been broadcast, just by a different process to the one that added it to @channels. Though perhaps it's just as possible that the `except!` on line 57 could cause actual loss if another process added an operation in the meantime.

**Comment by leastbad** [comment]
Hey Barry,

Yikes concurrency issues can be hard to track down. However, there's a good chance that you're running into a known Sidekiq issue. Did you know know that sk officially might run each operation more than once?

This means that if you're using the same queue for broadcasts as you fo for other tasks - maybe you shouldn't? - you have to make sure that your jobs are idempotent.

That means that you could have a status flag on a table, or you could create a key in Redis. Either way, if your job is idempotent, your problem should be moot via superior engineering - surely the most satisfying way to solve any problem.

**Comment by barrywoolgar** [comment]
Hello, thank you for your reply. The job I described above is idempotent, and I don't mind rendering the object more than once. And yes, I'm aware that Sidekiq runs multiple threads by default, and will retry jobs on failure. However my understanding is that having separate queues is a matter of defining priority, not a solution for concurrency issues.

The problem I'm reporting is that code in the gem is attempting to call a method on a nil reference. I'm not sure you've responded to that (my apologies if I've missed something), so should I take that to mean you don't feel it's a cable_ready problem? Do I need deal with the concurrency issue in the application code because the gem is not thread-safe? It doesn't feel right to rescue/ignore `NoMethodError, but the alternative is a lot of noise in my exception tracker even if everything works out fine in the end.

Also, to my understanding it would also be possible to define an operation and have it broadcast prematurely if another thread happens to call `cable_ready.broadcast` at the right time, even in a completely different context?

I've had some luck in my test case by wrapping all the cable_ready code in a mutex, but I'd have to share this mutex across my entire app to cover all the instances of cable_ready, as any one of them could unexpectedly clear the `@channels` hash and cause an exception elsewhere. This doesn't feel right either.

As I say, I'm not particularly experienced in concurrency issues (yet!), so please do. tell me if I've got the wrong end of the stick, but the simple solution seems to just be a nil check in the gem before cable_ready calls `broadcast` in its channels loop on line 56. If it is nil, then some other thread has got there first and has already broadcast the operation, no problem. 

What do you think?

**Comment by leastbad** [comment]
Thanks for clarifying. No need to jump to conclusions about what I'm "trying" to say, much less decide. We get a lot of requests for help from people who insist that they've covered the basics, but then they haven't - so you can appreciate that I have to ask questions about what you've tried.

I agree that it does seem as though two jobs are both attempting to operate on the same channels[identifier] object, and it is generating uncomfortable side effects.

Putting a `&` character before `.broadcast` would likely fix your logging in the short term, but ultimately I suspect that the contents of the `broadcast` and `broadcast_to` methods are going to need to be wrapped in a Mutex.

If you're already set up to do the work, could you try swapping out the `broadcast` method with this:

```ruby
def broadcast(*identifiers, clear: true)
  mutex = Mutex.new
  mutex.synchronize do
    @channels.values
      .reject { |channel| identifiers.any? && identifiers.exclude?(channel.identifier) }
      .select { |channel| channel.identifier.is_a?(String) }
      .tap do |channels|
        channels.each { |channel| @channels[channel.identifier].broadcast(clear) }
        channels.each { |channel| @channels.except!(channel.identifier) if clear }
      end
  end
end
```
then re-run your test scenario and tell me if you're still seeing the issue?

**Comment by barrywoolgar** [comment]
Hello, moving the mutex into the broadcast methods has resolved the problems I was seeing. I had to use a shared mutex to get it to work. I've submitted a PR with the changes.
