### ISSUE TITLE
Using morph with a document fragment appears to do a full replace instead of a morph

### ISSUE THREAD

**Issue by jasoncharnes** [hopsoft/cable_ready#67]
Hello all! 👋 

This is my first time in CableReady land, so please excuse my ignorance as I try to explain the issue we're running into. 🙏 

We're using CableReady's morph functionality. We're also using a `ViewComponent` that we want to re-render multiple times. It works pretty much flawlessly for us!

```ruby
cable_ready[channel].morph(
  selector: '#div-to-morph',
  html: ApplicationController.render(component)
)
```

👍 

Then, we encountered a case where we need to use a permanent attribute name. We have an image that we don't want to re-render each time. We updated our code to the following:

```ruby
cable_ready[channel].morph(
  selector: '#div-to-morph',
  html: ApplicationController.render(component),
  permanent_attribute_name: 'data-preview-permanent'
)
```

```erb
<div id="div-to-morph" class="<%= classes %>">
  <div data-preview-permanent>
    ... an image that should persist morphs...
  </div>
</div>
```

If we turn off browser caching, the image flickers (as it reloads) on each new morph call. This isn't caught when browser caching is on (unless you're using Safari, but that's another story for another time).

My co-worker @kylefox looked into CableReady and Morphom and learned that this does not happen if you change the `morphdom` [call in CableReady](https://github.com/hopsoft/cable_ready/blob/master/javascript/cable_ready.js#L163) to use `template.innerHTML` _instead of_ `template.content`. (This change does cause issues in StimulusReflex, though)

[Some deeper digging in Morphdom shows](https://github.com/patrick-steele-idem/morphdom/pull/168/files#diff-6de6ff83d7442f99b5bbb24d8cb5fd2dR1022-R1023) that when `morphdom` is given a DocumentFragment, it appears to do a full replace, versus morphing/diffing.

I believe this is _not_ an issue when using `childrenOnly`.

However, in our case- we don't use `childrenOnly`, we need the **entire** component morphed, including the parent.

From our understanding, `morph` currently only diffs **if** you're using `children_only: true` otherwise, it appears to do a full replace. 

---

@kylefox put together a [sample application with a walkthrough video](https://github.com/kylefox/cable_ready_morph_bug) to help support our findings.

I find this difficult to explain properly given I don't fully understand all the implications. However, I'm **more than glad** to help explain more/hop on a Zoom call to discuss further.

If we're mis-understanding the library, my apologies as well!

Thanks for all your hard work!

**Comment by leastbad** [comment]
You guys are murdering me with suspense.

Also, did you know this was a thing? https://github.com/hopsoft/cable_ready/pull/58

**Comment by kylefox** [comment]
Sorry for the delay @leastbad — took a while for me and @jasoncharnes to sync up on this issue again.

> @hopsoft has never let me patch morphdom, no matter how much I begged.

Genuinely curious — why work around bugs in dependencies instead of fixing bugs in dependencies?

I did end up opening a PR on morphdom to see if that project is open to patching the behavior: https://github.com/patrick-steele-idem/morphdom/pull/206 In the meantime, we've been using morphdom directly without CableReady to get around this issue.

> Are you suggesting that option 2 above would not solve your concern?

Option #2 would technically work, but it seems unnecessary to add yet another option. Especially because it feels like this is a scenario that should Just Work™ out of the box.

> Also, did you know this was a thing? #58

I didn't! I'll take a closer look at it.

**Comment by leastbad** [comment]
They have to be open to fixing those bugs, or acknowledge them as bugs. That project has been highly conservative wrt accepting patches for new features; what you're proposing is a breaking change, even if we successfully argue that it's a (very) positive one.

If the upstream dependency won't change, your options are:

- fork it, which @hopsoft didn't go for
- do nothing
- find clever ways to do what you need to do anyhow

None of which is a revelation, but sometimes you're between a rock and a hard place.

What is your plan for following-up on this, in terms of reaching out to the core team and how long you plan to give them to fix it before you evaluate one of the three options above?

I want to be clear and say that I want them to accept your PR very much, but I am skeptical that they will.

**Comment by kylefox** [comment]
Thanks @leastbad — that all makes sense. I guess we didn't realize morphdom was such an inactive project 😕 

> What is your plan for following-up on this, in terms of reaching out to the core team and how long you plan to give them to fix it before you evaluate one of the three options above?

Good question. We'll probably give it a week or two to see if anything develops on the morphdom PR. If nothing happens (and I'm getting a bit skeptical myself) then I'd love to explore an option in CableReady that just works automatically — something like [what you proposed in option (3)](https://github.com/hopsoft/cable_ready/issues/67#issuecomment-678671004) or what was suggested in #58.

**Comment by leastbad** [comment]
I don't know if it's inactive or just highly change resistant. I empathize because it's not clear Patrick knew he was creating critical infrastructure. When you're talking about subtle behaviour changes, you have to weigh them against breaking (potentially thousands of) production apps in unexpected ways.

Although, I thought that's what SemVer was supposed to fix...

**Comment by hopsoft** [comment]
For the record, I'm completely in favor of submitting patches to upstream dependencies. I'm just opposed to maintaining a bespoke fork of those dependencies.

I agree that is something that should simply work out of the box, so option 3 sounds like a reasonable path to take. I'll spend some time experimenting with #58 as it seems like it may address this issue. If you happen to test #58 yourself, please report any findings on this issue. 🙏

**Comment by leastbad** [comment]
Based on @joshleblanc's PR #58 it sounds like he's tested it with desirable outcomes:

> This change results in my test project successfully rendering with children_only set to true or false, always respecting the permanent attribute.

That sounds pretty darn good to me, given that `childrenOnly = true` remains the default. This is only a breaking change for people using `childrenOnly = false`, with theoretically very positive outcomes for them.

I am trying hard to think of a downside to just accepting #58.

**Comment by kylefox** [comment]
It appears that #58 fixes our issue, but to be honest I don't fully understand why there needs to be [a conditional](https://github.com/hopsoft/cable_ready/pull/58/files#diff-ca2331ae1bbdc7543d9a0fd46141bd58R163). From what I can tell, morphdom shouldn't be passed a `DocumentFragment` as the second argument in the first place, because it never performs a diff anyway 🤷

**Comment by joshleblanc** [comment]
It's been awhile, but I'm pretty sure I made it a conditional because I didn't want to break anything unintentionally. So it would behave as it does in all cases except childrenOnly

**Comment by jasoncharnes** [comment]
I'm going to close this out in favor of #58
