### ISSUE TITLE
CableReady detected an error in insertAdjacentHtml. Object doesn't support this action - IE11 only

### ISSUE THREAD

**Issue by artur79** [hopsoft/cable_ready#76]
As in the title, error appears on IE11 only.

**Comment by braindeaf** [comment]
@artur79 and I found the solution actually. The following polyfills fix the issue.

https://developer.aliyun.com/mirror/npm/package/@stimulus_reflex/polyfills

**Comment by artur79** [comment]
> @artur79 and I found the solution actually. The following polyfills fix the issue.
> 
> https://developer.aliyun.com/mirror/npm/package/@stimulus_reflex/polyfills

works :)
